// Reads the Teams Planner exports under ./OKR and emits supabase/import_gst.sql
// mapping them to AEO: Company → Team objectives → KRs → Action Plans / Critical 6.
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
const require = createRequire(import.meta.url);
const XLSX = require('xlsx');

const OWNER = "(select id from public.users where email='cb.park@ohmyhotel.com')";
const SRC = "'planner'";
const U = (n) => `'00000000-0000-4000-8000-0000000000${n}'`; // quoted fixed-id literal
const COMPANY = U('01');
const GST_OBJ = U('a1');
const C_KR = (i) => U('c' + i);   // company KR1..5
const GST_KR = (i) => U('d' + i); // GST team KR1..5

// ---- helpers ---------------------------------------------------------------
const clean = (s) => String(s ?? '').replace(/[​-‍﻿]/g, '').replace(/\s+/g, ' ').trim();
const q = (s) => { const c = clean(s); return c ? `'${c.replace(/'/g, "''")}'` : 'null'; };
const qtrunc = (s, n = 280) => q(clean(s).slice(0, n));
const dateQ = (s) => { const c = clean(s); return /^\d{4}-\d{2}-\d{2}$/.test(c) ? `'${c}'` : 'null'; };
const arr = (items) => {
  const xs = items.map((x) => clean(x)).filter(Boolean);
  return xs.length ? `array[${xs.map((x) => `'${x.replace(/'/g, "''")}'`).join(',')}]::text[]` : `'{}'::text[]`;
};
const splitList = (s) => clean(s).split(/;|\n/).map(clean).filter(Boolean);
const STATUS = { '시작 안 함': 'not_started', '진행 중': 'in_progress', '완료': 'completed' };
const PRIO = { '낮음': 'low', '중간': 'medium', '중요': 'important', '긴급': 'urgent' };
const mapStatus = (s, delayed) => {
  const v = STATUS[clean(s)] ?? 'not_started';
  return v;
};
const mapPrio = (p) => PRIO[clean(p)] ?? 'medium';
const checklistJson = (s, done) => {
  const items = splitList(s).map((text, i) => ({ id: 'c' + i, text, done: !!done }));
  if (!items.length) return `'[]'::jsonb`;
  return `'${JSON.stringify(items).replace(/'/g, "''")}'::jsonb`;
};
const krForBucket = (name, krFn) => {
  const n = clean(name);
  if (/KR1|Active 1000|채널 Active/.test(n)) return krFn(1);
  if (/KR2|Daily 7000/.test(n)) return krFn(2);
  if (/KR3|TTV ?50|Tier0/.test(n)) return krFn(3);
  if (/KR4|중화권/.test(n)) return krFn(4);
  if (/KR5|Reve?nue|260/.test(n)) return krFn(5);
  return null;
};

const sheet = (file, name) => XLSX.utils.sheet_to_json(XLSX.readFile(file).Sheets[name], { header: 1, defval: '' });
const rows = (file) => sheet(file, '통합 데이터').slice(1).filter((r) => clean(r[1]));
// columns: 0 id,1 name,2 bucket,3 goal,4 status,5 prio,6 assignees,8 created,9 due,10 start,12 delayed,13 done_date,16 checklist,17 labels,18 note
const COL = { id: 0, name: 1, bucket: 2, status: 4, prio: 5, assignees: 6, due: 9, start: 10, delayed: 12, doneDate: 13, checklist: 16, labels: 17, note: 18 };

const OKR_F = 'OKR/1. OKR/0. HQ/HQ - OKR 2026.xlsx';
const GST_F = 'OKR/1. OKR/1. GSM/GST_OKR2026.xlsx';
const AP_F = 'OKR/2. Action Plan/1. Sales/Action Plan (1).xlsx';
const C6_F = 'OKR/3. Ctritical6/1. Aiden/GST_Critical6.xlsx';

const out = [];
const P = (s) => out.push(s);

P(`-- Generated by scripts/genimport.mjs — Teams Planner -> AEO. Re-runnable.`);
P(`-- Run AFTER 0008_planner_import.sql. Owner of imported rows = cb.park@ohmyhotel.com.`);
P(`begin;`);
P(`update public.users set role='admin' where email='cb.park@ohmyhotel.com';`);

// idempotent cleanup of any prior import
for (const t of ['critical_six', 'action_plans', 'key_results', 'objectives'])
  P(`delete from ${t} where external_source=${SRC};`);
P(`delete from people where planner_user_id is not null;`);

// ---- teams -----------------------------------------------------------------
// team code (prefix before ':') -> slug
const TEAM_NAMES = { GST: 'GST', OTA: 'OTA', DI: 'DI', OP: 'OP', GBO: 'GBO', MKT: 'MKT', IT: 'IT', SAS: 'SAS',
  'JP SCM': 'JP SCM', 'KR SCM': 'KR SCM', 'GC SCM': 'GC SCM', 'AI Planning': 'AI Planning',
  'KR 경영지원': '경영지원', '경영지원': '경영지원', 'OMH': 'HQ' };
const teamCode = (taskName) => {
  const m = clean(taskName).match(/^([A-Za-z가-힣 ]+?)\s*:/);
  return m ? m[1].trim() : null;
};
const slugify = (code) => code.toLowerCase().replace(/[^a-z0-9가-힣]+/g, '-').replace(/^-|-$/g, '');
const seenTeams = new Map();
const ensureTeam = (code) => {
  const name = TEAM_NAMES[code] ?? code;
  const slug = slugify(name);
  if (!seenTeams.has(slug)) {
    seenTeams.set(slug, name);
    P(`insert into teams (name, slug, created_by) values (${q(name)}, ${q(slug)}, ${OWNER}) on conflict (slug) do nothing;`);
  }
  return `(select id from teams where slug=${q(slug)})`;
};
const ensureMember = (teamExpr) =>
  P(`insert into team_members (team_id, user_id, team_role, created_by) select ${teamExpr}, ${OWNER}, 'leader', ${OWNER} where ${OWNER} is not null on conflict (team_id, user_id) do nothing;`);

// ---- people roster (union of all 사용자 sheets) ----------------------------
const people = new Map();
for (const f of [OKR_F, GST_F, AP_F, C6_F]) {
  for (const r of sheet(f, '사용자').slice(1)) {
    const [pid, name, email] = [clean(r[0]), clean(r[1]), clean(r[2])];
    if (email && !people.has(email)) people.set(email, { pid, name, email });
  }
}
for (const p of people.values())
  P(`insert into people (full_name, email, planner_user_id, user_id, created_by) values (${q(p.name)}, ${q(p.email)}, ${q(p.pid)}, (select id from public.users where email=${q(p.email)}), ${OWNER}) on conflict (email) do nothing;`);

// ---- Company objective + company KRs (HQ file) -----------------------------
P(`\n-- Company (HQ / OMH)`);
P(`insert into objectives (id, title, description, level, owner_id, status, priority, year, external_id, external_source, created_by) values (${COMPANY}, '오마이호텔(OMH) 2026', 'HQ 회사 전사 OKR — 글로벌 확장·매출 성장·AI 내재화·브랜드 강화', 'company', ${OWNER}, 'in_progress', 'critical', 2026, 'hq-2026', ${SRC}, ${OWNER});`);

let ci = 0;
for (const r of rows(OKR_F)) {
  const b = clean(r[COL.bucket]);
  if (b === 'Company OKR') {
    ci++;
    P(`insert into key_results (id, objective_id, title, description, owner_id, status, priority, external_id, external_source, created_by) values (${C_KR(ci)}, ${COMPANY}, ${q(r[COL.name])}, ${qtrunc(r[COL.note])}, ${OWNER}, '${mapStatus(r[COL.status])}', '${mapPrio(r[COL.prio])}', ${q(r[COL.id])}, ${SRC}, ${OWNER});`);
  }
}

// ---- Team objectives (HQ file: *Team OKR / 경영지원 buckets) ----------------
P(`\n-- Team objectives`);
for (const r of rows(OKR_F)) {
  const b = clean(r[COL.bucket]);
  if (!/Team OKR|경영지원/.test(b)) continue;
  const code = teamCode(r[COL.name]);
  if (code !== 'GST') continue;   // our team only — skip other teams' OKR
  const teamExpr = ensureTeam(code);
  ensureMember(teamExpr);
  const isGst = code === 'GST';
  const idExpr = isGst ? `${GST_OBJ}` : 'gen_random_uuid()';
  P(`insert into objectives (id, title, description, level, owner_id, team_id, parent_objective_id, status, priority, year, external_id, external_source, created_by) values (${idExpr}, ${qtrunc(r[COL.name], 200)}, ${qtrunc(r[COL.note])}, 'team', ${OWNER}, ${teamExpr}, ${COMPANY}, '${mapStatus(r[COL.status])}', '${mapPrio(r[COL.prio])}', 2026, ${q(r[COL.id])}, ${SRC}, ${OWNER});`);
}

// ---- GST team KR1..5 (GST file: KR buckets define them) ---------------------
P(`\n-- GST team Key Results`);
const GST_KR_DEF = [
  [1, 'KR1 Active Channel 1000', 'active_channel_count', 1000, '개 채널'],
  [2, 'KR2 Daily Booking 7000', 'booking_count', 7000, '건/일'],
  [3, 'KR3 Tier0 (월 TTV 50억) 3곳', 'tier0_count', 3, '곳'],
  [4, 'KR4 중화권 비중 65%로 균형', 'china_share_pct', 65, '%'],
  [5, 'KR5 Revenue 260억', 'revenue', 260, '억원'],
];
for (const [i, title, metric, target, unit] of GST_KR_DEF)
  P(`insert into key_results (id, objective_id, title, metric_type, target_value, current_value, unit, owner_id, status, priority, external_source, created_by) values (${GST_KR(i)}, ${GST_OBJ}, ${q(title)}, '${metric}', ${target}, 0, ${q(unit)}, ${OWNER}, 'in_progress', 'important', ${SRC}, ${OWNER});`);

const GST_TEAM = `(select id from teams where slug='gst')`;

// ---- Action Plans (GST file KR-bucket tasks + Action Plan file) ------------
P(`\n-- Action Plans`);
const apInsert = (r, krExpr) => {
  const completed = clean(r[COL.status]) === '완료';
  P(`insert into action_plans (title, description, key_result_id, objective_id, team_id, owner_id, external_assignees, status, priority, bucket, labels, checklist, start_date, due_date, external_id, external_source, data_source, created_by) values (${qtrunc(r[COL.name], 200)}, ${qtrunc(r[COL.note])}, ${krExpr ?? 'null'}, ${krExpr ? 'null' : GST_OBJ}, ${GST_TEAM}, ${OWNER}, ${arr(splitList(r[COL.assignees]))}, '${mapStatus(r[COL.status])}', '${mapPrio(r[COL.prio])}', ${q(r[COL.bucket])}, ${arr(splitList(r[COL.labels]))}, ${checklistJson(r[COL.checklist], completed)}, ${dateQ(r[COL.start])}, ${dateQ(r[COL.due])}, ${q(r[COL.id])}, ${SRC}, 'planner', ${OWNER});`);
};
for (const r of rows(GST_F)) {
  const kr = krForBucket(r[COL.bucket], GST_KR);
  if (kr) apInsert(r, kr); // only KR-bucket tasks become action plans (objects/krs handled above)
}
for (const r of rows(AP_F)) {
  const kr = krForBucket(clean(r[COL.labels]) + ' ' + clean(r[COL.bucket]), GST_KR);
  apInsert(r, kr);
}

// ---- Critical 6 (Critical6 file) ------------------------------------------
P(`\n-- Critical 6`);
for (const r of rows(C6_F)) {
  const kr = krForBucket(r[COL.bucket], GST_KR);
  const completed = clean(r[COL.status]) === '완료';
  P(`insert into critical_six (title, description, key_result_id, objective_id, team_id, owner_id, external_assignees, status, priority, completion_criteria, blocker, completed_at, due_date, external_id, external_source, created_by) values (${qtrunc(r[COL.name], 200)}, ${qtrunc(r[COL.note])}, ${kr ?? 'null'}, ${GST_OBJ}, ${GST_TEAM}, ${OWNER}, ${arr(splitList(r[COL.assignees]))}, '${mapStatus(r[COL.status])}', '${mapPrio(r[COL.prio])}', ${qtrunc(splitList(r[COL.checklist]).join(' · '), 280)}, null, ${completed ? `(${dateQ(r[COL.doneDate])}::timestamptz)` : 'null'}, ${dateQ(r[COL.due])}, ${q(r[COL.id])}, ${SRC}, ${OWNER});`);
}

P(`commit;`);
writeFileSync('supabase/import_gst.sql', out.join('\n') + '\n');
console.log(`wrote supabase/import_gst.sql — ${out.length} statements, ${people.size} people, ${seenTeams.size} teams`);
